services:
  - type: web
    name: django-assessment
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn assessment.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: SECRET_KEY
        generateValue: true
    plan: free
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1 